### ISSUE TITLE
Document and improve kyma release process

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#106]
**Description**
The first release of kyma-project is out. In order to make a next release less painfull several actions should be taken:
- [x] document current release process (used for the first release)
- [x] automate some manual steps to simplify and speed up the process
- [x] implement the process in the new CI/CD tool (Prow)
- [x] review, adapt and create a new version of the release process that will be used in next releases

**Comment by lszymik** [comment]
Please take a look if that ticket requires further processing.

**Comment by pbochynski** [comment]
Done with prow migration.
