### ISSUE TITLE
Remove TWs that are no longer active contributors from CODEOWNERS

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/community#580]
**Description**

Several TWs have left the organization and haven't been actively contributing to the project for over 3 months, therefore, as per the [Kyma Ownership policy](https://github.com/kyma-project/community/blob/main/governance/01-governance.md#when-does-a-maintainer-lose-the-maintainer-status), they must be removed from CODEOWNERS.

**Related PRs**

- [x] kyma-project/test-infra#4051
- [x] kyma-project/hydroform#335
- [x] kyma-project/helm-broker#169
- [x] kyma-project/console#2216
- [x] kyma-project/community#579
- [x] kyma-project/website#759
- [x] kyma-project/cli#957
- [x] kyma-project/addons#159
- [x] kyma-project/third-party-images#113
- [x] kyma-project/examples#181
