### ISSUE TITLE
Update the content in the "community" repo

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/community#604]
**Description**

We have a lot of outdated and redundant content in the `community` repo, that's why we need to revisit these docs, check with SMEs if the instructions and descriptions of processes are up-to-date, and remove and/or update the content. As it would be difficult and tiring to handle by one person, it's better to divide it into chunks that can be handled simultaneously by different TWs. This is the proposed task division:

- [ ] Update the [Contributing](https://kyma-project.io/community/contributing/) section. Revisit the `Contributing rules` document and confirm whether we still need the sections about `Agreements and licences` (contact @pbochynski for more info). For the rest of the document, think of making it more concise and either remove the redundant parts or chunk the content into shorter docs. Some part may also be moved to the governance section. As for the `Git workflow` document, keep the basic rules but remove all the workflow part and link to Github documentation instead.
- [ ] Update the [Governance](https://kyma-project.io/community/governance/) section.
- [ ] Update the [Release guidelines](https://kyma-project.io/community/guidelines/releases-guidelines/) section. Some sections (for example the one about how to prepare a Kyma release) should not be included in the website as it's rather more internal.
- [ ] Update the [Repository guidelines](https://kyma-project.io/community/guidelines/repository-guidelines/) and [Technical guidelines](https://kyma-project.io/community/guidelines/technical-guidelines/) sections

**Area**

area/documentation
area/community?

**Reasons**

There is a lot of outdated and redundant content in the `community` repo that is not maintained.

**Assignees**

@kyma-project/technical-writers
