### ISSUE TITLE
Module Developer Documentation and Onboarding Material

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/community#700]
For Developing Modules, we want to make sure that Developers have sufficient Material available to effectively develop without having to involve with the entire Architecture Stack of Modularization at once. For this we need to. develop a consistent documentation and onboarding experience that can be shared, reused and edited on demand

AC:
- [x] Module gets a Description and Specification reference in community / concepts at [Modularization concept by pbochynski · Pull Request kyma-project/community#666 · kyma-project/community (github.com)](https://github.com/kyma-project/community/pull/666) -> Is updated with OCM / OCI References
- [x] CLI Documentation is put into CLI Repo always for new commands - References Modularization concept
- [x] Operator Reconciliation gets a Description and Specification reference in [Architectural concept for operator-based reconciliation by jakobmoellersap · Pull Request kyma-project/community#654 · kyma-project/community (github.com)](https://github.com/kyma-project/community/pull/654) -> References Modularization concept and CLI Documentation
- [x] How to Build and Deploy a Module 
    - [x] kyma-project/lifecycle-manager#279
    - [x] extend Step-By-Step Guide to cover also Kustomize and RAW manifests
    - [x] publish the guides in the OS repository (as readme with references Modularization concept and CLI Documentation, Operator Reconciliation)
- [x] Reference implementation for a module operator in https://github.com/kyma-project/kyma-operator/tree/main/samples/template-operator 
- [x] Rework high level overview operator reconciliation (https://github.com/kyma-project/community/pull/654)
- [x] https://github.com/kyma-project/runtime-watcher/issues/58

**Comment by NHingerl** [comment]
It's needed for all three topics, right? 
And the topic owners are @adityabhatia, @khlifi411 and @jeremyharisch?

**Comment by NHingerl** [comment]
And we're talking only about [column 8 of this mural](https://app.mural.co/t/sapcloudplatform5636/m/sapcloudplatform5636/1657632170651/cd924a662554e951401b24334ab41ea76142241a?sender=u18ddb126c7e2156f766f8551) of which docs are needed?

**Comment by tobiscr** [comment]
Depends on https://github.com/kyma-project/kyma-operator/issues/115

**Comment by NHingerl** [comment]
On hold for now:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/76950046/194884040-0c2e624b-e7e9-4854-afe2-fc0f5ee1d7f2.png">

**Comment by jakobmoellersap** [comment]
Step-By-Step Guide Implemented in https://github.com/kyma-project/lifecycle-manager/blob/main/samples/template-operator/README.md
